networks:
  hyperion:
    chain_id: 133717
    explorer_url: https://hyperion-testnet-explorer.metisdevops.link
    rpc_url: https://hyperion-testnet.metisdevops.link
    status: testnet
    default: true
ai_providers:
  google:
    api_key: ""
    # Model selection is now automatic based on token optimization
    # Preferred models (auto-selected): gemini-2.0-flash-lite, gemini-2.5-flash-lite
    # Fallback: gemini-2.5-pro for large tasks
    model: "auto"  # Auto-selection enabled
  openai:
    api_key: ""
    model: "gpt-4o-mini"  # Fallback only
  anthropic:
    api_key: ""
    model: "claude-3-sonnet"

