ai_providers:
  google:
    api_key: 'YOUR_GOOGLE_API_KEY_HERE'
    model: 'gemini-pro'
  openai:
    api_key: 'YOUR_OPENAI_API_KEY_HERE'
    model: 'gpt-4'
  anthropic:
    api_key: 'YOUR_ANTHROPIC_API_KEY_HERE'
    model: 'claude-3-sonnet'

networks:
  # HYPERION-ONLY CONFIGURATION
  # Future network support (LazAI, Metis) documented in ROADMAP.md only
  # No multi-network logic - Hyperion is the exclusive deployment target
  
  hyperion:
    chain_id: 133717
    explorer_url: https://hyperion-testnet-explorer.metisdevops.link
    rpc_url: https://hyperion-testnet.metisdevops.link
    status: testnet
    default: true  # Hardcoded default - no network selection

security:
  enable_audit: true
  enable_verification: true
  private_key: ''

test_key: test_value
