ai_providers:
  google:
    api_key: 'YOUR_GOOGLE_API_KEY_HERE'
    model: 'gemini-pro'
  openai:
    api_key: 'YOUR_OPENAI_API_KEY_HERE'
    model: 'gpt-4'
  anthropic:
    api_key: 'YOUR_ANTHROPIC_API_KEY_HERE'
    model: 'claude-3-sonnet'

networks:
  # Primary Network: Hyperion Testnet (Mainnet Coming Soon)
  hyperion:
    chain_id: 1001
    explorer_url: https://hyperion-testnet-explorer.metisdevops.link
    rpc_url: https://hyperion-testnet.metisdevops.link
    status: testnet
    mainnet_coming_soon: true
  
  # Primary Network: LazAI Testnet (Mainnet Coming Soon)
  lazai:
    chain_id: 8888  # Update with actual chain ID
    explorer_url: https://lazai-explorer.example.com  # Update with actual explorer
    rpc_url: https://lazai-testnet-rpc.example.com  # Update with actual RPC
    status: testnet
    mainnet_coming_soon: true
  
  # Primary Network: Metis Mainnet
  metis:
    chain_id: 1088
    explorer_url: https://andromeda-explorer.metis.io
    rpc_url: https://andromeda.metis.io/?owner=1088
    status: mainnet
    mainnet_coming_soon: false

security:
  enable_audit: true
  enable_verification: true
  private_key: ''

test_key: test_value
