# HyperKit AI Agent - Main Configuration File
# This file contains all system settings and network configurations

# AI Provider Configuration
ai_providers:
  google:
    enabled: true
    model: "gemini-2.5-pro-preview-03-25"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 8192
    temperature: 0.7
  
  # Cloud-based providers
  openai:
    enabled: true
    model: "gpt-4o-mini"
    api_key_env: "OPENAI_API_KEY"
    max_tokens: 4096
    temperature: 0.7
  
  anthropic:
    enabled: false
    model: "claude-3-sonnet"
    api_key_env: "ANTHROPIC_API_KEY"

# Blockchain Network Configuration - HYPERION/METIS/LAZAI FOCUS
networks:
  hyperion:
    name: "Hyperion Testnet"
    rpc_url: "https://hyperion-testnet.metisdevops.link"
    chain_id: 133717
    explorer_url: "https://hyperion-testnet-explorer.metisdevops.link"
    gas_price: "20000000000"  # 20 gwei
    gas_limit: 8000000
    enabled: true
    priority: 1
  
  metis:
    name: "Metis Andromeda"
    rpc_url: "https://andromeda.metis.io"
    chain_id: 1088
    explorer_url: "https://andromeda-explorer.metis.io"
    gas_price: "20000000000"  # 20 gwei
    gas_limit: 8000000
    enabled: true
    priority: 2
  
  lazai:
    name: "LazAI Testnet"
    rpc_url: "https://rpc.lazai.network/testnet"
    chain_id: 9001
    explorer_url: "https://testnet-explorer.lazai.network"
    gas_price: "1000000000"  # 1 gwei
    gas_limit: 8000000
    enabled: true
    priority: 3

# Default Settings
defaults:
  network: "hyperion"
  ai_provider: "google"
  log_level: "INFO"
  max_retries: 3
  timeout: 30

# RAG Configuration (Simple MCP)
rag_system:
  enabled: true
  method: "simple_mcp"  # Options: "simple_mcp", "api", "file"
  api_key_env: "OBSIDIAN_API_KEY"
  mcp_config:
    api_key_env: "OBSIDIAN_API_KEY"
    api_url: "http://localhost:27124"  # Direct Obsidian API
  max_context_length: 4000
  chunk_size: 1000
  chunk_overlap: 200

# LangChain Configuration (Removed - using simple MCP instead)

# Security Configuration
security:
  slither:
    enabled: true
    timeout: 60
    exclude_informational: false
  
  mythril:
    enabled: false  # Disabled due to Windows compatibility issues
    timeout: 120
  
  edb:
    enabled: false  # Disabled due to Windows compatibility issues
  
  custom_patterns:
    enabled: true
    patterns_file: "./config/security_patterns.json"

# Deployment Configuration
deployment:
  auto_verify: true
  verification_delay: 10  # seconds
  max_gas_price: "50000000000"  # 50 gwei
  min_balance: "1000000000000000000"  # 1 ETH
  
  constructor_args:
    # Default constructor arguments for common contract types
    erc20:
      - "Test Token"  # name
      - "TEST"        # symbol
      - 1000000       # initial supply (with 18 decimals)
    
    erc721:
      - "Test NFT"    # name
      - "TNFT"        # symbol
      - "https://api.example.com/metadata/"  # base URI

# Monitoring Configuration
monitoring:
  enabled: true
  check_interval: 5  # seconds
  confirmation_blocks: 12
  max_monitoring_time: 3600  # 1 hour
  
  alerts:
    email: false
    webhook: false
    console: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"]
  
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Database Configuration
database:
  type: "sqlite"
  url: "sqlite:///./hyperkit-agent.db"
  
  redis:
    enabled: false
    url: "redis://localhost:6379"

# Logging Configuration
logging:
  level: "INFO"
  file_path: "./logs/hyperkit-agent.log"
  max_size: 10
  backup_count: 5
  format: "text"

# Development Configuration
development:
  hot_reload: false
  debug_mode: false
  mock_external_apis: false
  test_mode: false
