ai_providers:
  google_api_key: ''
  lazai_rsa_private_key: ''
  openai_api_key: ''
networks:
  ethereum:
    chain_id: 1
    explorer_url: https://etherscan.io
    rpc_url: https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
  hyperion:
    chain_id: 1001
    explorer_url: https://hyperion-testnet-explorer.metisdevops.link
    rpc_url: https://hyperion-testnet.metisdevops.link
security:
  enable_audit: true
  enable_verification: true
  private_key: ''
test_key: test_value
