ai_providers:
  google:
    api_key: 'YOUR_GOOGLE_API_KEY_HERE'
    model: 'gemini-pro'
  openai:
    api_key: 'YOUR_OPENAI_API_KEY_HERE'
    model: 'gpt-4'
  anthropic:
    api_key: 'YOUR_ANTHROPIC_API_KEY_HERE'
    model: 'claude-3-sonnet'
networks:
  ethereum:
    chain_id: 1
    explorer_url: https://etherscan.io
    rpc_url: https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
  hyperion:
    chain_id: 1001
    explorer_url: https://hyperion-testnet-explorer.metisdevops.link
    rpc_url: https://hyperion-testnet.metisdevops.link
security:
  enable_audit: true
  enable_verification: true
  private_key: ''
test_key: test_value