[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"  # Updated for OpenZeppelin v5 compatibility (requires ^0.8.24)
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
include_storage = true
include_push_bytes = true
dictionary_weight = 80
