#!/bin/bash
# Legacy File Cleanup Script
# Generated by legacy_file_inventory.py

echo "Starting legacy file cleanup..."

# Create archive directory
mkdir -p ARCHIVE/legacy_files
mkdir -p ARCHIVE/not_implemented

# Add NOT IMPLEMENTED banners to disaster recovery files
echo "Adding NOT IMPLEMENTED banners to disaster recovery files..."

# Add banner to DISASTER_RECOVERY.md
if [ -f "docs/EXECUTION/DISASTER_RECOVERY.md" ]; then
    echo "Adding NOT IMPLEMENTED banner to docs/EXECUTION/DISASTER_RECOVERY.md..."
    cp "docs/EXECUTION/DISASTER_RECOVERY.md" "docs/EXECUTION/DISASTER_RECOVERY.md.backup"
    
    cat > "docs/EXECUTION/DISASTER_RECOVERY.md.tmp" << 'EOF'
> **NOT IMPLEMENTED BANNER**  
> This process references scripts or procedures that are not CLI-integrated.  
> These features are documented but not executable via `hyperagent` CLI.  
> See implementation status in `REPORTS/IMPLEMENTATION_STATUS.md`.
> 
> 
> 
EOF
    
    cat "docs/EXECUTION/DISASTER_RECOVERY.md" >> "docs/EXECUTION/DISASTER_RECOVERY.md.tmp"
    mv "docs/EXECUTION/DISASTER_RECOVERY.md.tmp" "docs/EXECUTION/DISASTER_RECOVERY.md"
    echo "Added NOT IMPLEMENTED banner to docs/EXECUTION/DISASTER_RECOVERY.md"
fi

# Add banner to EMERGENCY_RESPONSE.md
if [ -f "docs/EMERGENCY_RESPONSE.md" ]; then
    echo "Adding NOT IMPLEMENTED banner to docs/EMERGENCY_RESPONSE.md..."
    cp "docs/EMERGENCY_RESPONSE.md" "docs/EMERGENCY_RESPONSE.md.backup"
    
    cat > "docs/EMERGENCY_RESPONSE.md.tmp" << 'EOF'
> **NOT IMPLEMENTED BANNER**  
> This process references scripts or procedures that are not CLI-integrated.  
> These features are documented but not executable via `hyperagent` CLI.  
> See implementation status in `REPORTS/IMPLEMENTATION_STATUS.md`.
> 
> 
> 
EOF
    
    cat "docs/EMERGENCY_RESPONSE.md" >> "docs/EMERGENCY_RESPONSE.md.tmp"
    mv "docs/EMERGENCY_RESPONSE.md.tmp" "docs/EMERGENCY_RESPONSE.md"
    echo "Added NOT IMPLEMENTED banner to docs/EMERGENCY_RESPONSE.md"
fi

echo "Legacy file cleanup completed!"
echo "Review files with NOT IMPLEMENTED banners"
echo "Backup files created with .backup extension"
