#!/bin/bash
# Legacy File Cleanup Script
# Generated by legacy_file_inventory.py

echo "Starting legacy file cleanup..."

# Create archive directory
mkdir -p ARCHIVE/legacy_files
mkdir -p ARCHIVE/not_implemented

# Archive files with multiple legacy references

# Archive .\hyperkit-agent\scripts\ci\README.md - Multiple legacy script references
if [ -f ".\hyperkit-agent\scripts\ci\README.md" ]; then
    echo "Archiving .\hyperkit-agent\scripts\ci\README.md..."
    mv ".\hyperkit-agent\scripts\ci\README.md" "ARCHIVE/legacy_files/"
    echo "Archived .\hyperkit-agent\scripts\ci\README.md"
fi

# Archive .\hyperkit-agent\scripts\maintenance\README.md - Multiple legacy script references
if [ -f ".\hyperkit-agent\scripts\maintenance\README.md" ]; then
    echo "Archiving .\hyperkit-agent\scripts\maintenance\README.md..."
    mv ".\hyperkit-agent\scripts\maintenance\README.md" "ARCHIVE/legacy_files/"
    echo "Archived .\hyperkit-agent\scripts\maintenance\README.md"
fi

# Add NOT IMPLEMENTED banners to files

# Add NOT IMPLEMENTED banner to .\hyperkit-agent\docs\EMERGENCY_RESPONSE.md
if [ -f ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md" ]; then
    echo "Adding NOT IMPLEMENTED banner to .\hyperkit-agent\docs\EMERGENCY_RESPONSE.md..."
    # Create backup
    cp ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md" ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md.backup"
    
    # Add banner
    cat > ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md.tmp" << 'EOF'
> **NOT IMPLEMENTED BANNER**  
> This process references scripts or procedures that are not CLI-integrated.  
> These features are documented but not executable via `hyperagent` CLI.  
> See implementation status in `REPORTS/IMPLEMENTATION_STATUS.md`.
> 
> 
> 
EOF
    
    cat ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md" >> ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md.tmp"
    mv ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md.tmp" ".\hyperkit-agent\docs\EMERGENCY_RESPONSE.md"
    echo "Added NOT IMPLEMENTED banner to .\hyperkit-agent\docs\EMERGENCY_RESPONSE.md"
fi

echo "Legacy file cleanup completed!"
echo "Review ARCHIVE/ directory for archived files"
echo "Review files with NOT IMPLEMENTED banners"
