name: Changeset Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  changeset-check:
    name: Check for Changeset
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check changeset status
        run: |
          echo "Checking changeset status..."
          if [ -d ".changeset" ]; then
            echo "✅ Changeset directory found"
            ls -la .changeset/
          else
            echo "❌ No changeset directory found"
            exit 1
          fi
      
      - name: Verify changeset presence
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Checking if PR has changeset..."
            if [ -d ".changeset" ] && [ "$(find .changeset -name "*.md" -not -name "README.md" | wc -l)" -gt 0 ]; then
              echo "✅ Changeset found for this PR"
              find .changeset -name "*.md" -not -name "README.md"
            else
              echo "❌ No changeset found for this PR"
              echo "Please run 'npx changeset' to create a changeset"
              exit 1
            fi
          fi
      
      - name: Validate changeset format
        run: |
          if [ -d ".changeset" ]; then
            echo "Validating changeset files..."
            for file in .changeset/*.md; do
              if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
                echo "Validating $file"
                if ! grep -q "---" "$file" || ! grep -q "---" "$file" -A 1 | grep -q "---"; then
                  echo "❌ Invalid changeset format in $file"
                  exit 1
                fi
                echo "✅ $file is valid"
              fi
            done
          fi
